name: Action Practice

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Workflow Message
        run: echo "Now running build workflow"

      - name: Ending Workflow Message
        run: |
          echo "Now ending build workflow"
          echo "Have a great day"

  repo_forked:
    runs-on: ubuntu-latest
    if: github.event_name == 'fork'
    needs: build
    env:
      user: Steven Universe
    steps:
      - name: Inform Steven
        run: |
          echo "Hello $user, this job is about to end."
          echo "Job has ended."
